name: "Puppet"
description: "Turn dashboards into nice pictures"
version: "1.18.1"
slug: "puppet"
homeassistant_api: true
init: false
arch:
  - aarch64
  - amd64
ports:
  10000/tcp: 10000
options:
  access_token: ""
  home_assistant_url: "http://homeassistant:8123"
schema:
  access_token: str
  home_assistant_url: str
